import { useState } from 'react';
import { Copy, Check } from 'lucide-react';

interface AdvocacyChecklistProps {
  questions: string[];
  doctorType?: string;
}

export default function AdvocacyChecklist({ questions, doctorType }: AdvocacyChecklistProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = questions.map((q, i) => `${i + 1}. ${q}`).join('\n');
    const header = `Questions for my ${doctorType ?? 'doctor'} — generated by Lumina\n\n`;
    await navigator.clipboard.writeText(header + text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="bg-[#FAF6F2]/65 border border-[#F4DFD7] rounded-3xl p-8 space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <h3 className="font-serif text-2xl md:text-3xl font-semibold text-[#5D3754] flex items-center gap-2">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-[#8FA998]">
              <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/>
              <path d="m9 12 2 2 4-4"/>
            </svg>
            Advocacy Checklist
          </h3>
          <p className="text-xs text-[#5D3754]/80">
            Take these questions to your next appointment. You deserve clarity and partnership.
          </p>
        </div>
        
        <button
          onClick={handleCopy}
          className="self-start sm:self-auto inline-flex items-center gap-1.5 font-sans text-xs font-semibold border border-[#5D3754] text-[#5D3754] hover:bg-[#5D3754] hover:text-[#FAF6F2] px-4 py-2 rounded-full transition-all duration-200"
        >
          {copied ? (
            <>
              <Check size={13} />
              Copied!
            </>
          ) : (
            <>
              <Copy size={13} />
              Copy Questions
            </>
          )}
        </button>
      </div>

      {/* Grid of Checklist Questions (Matching Image 2) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {questions.slice(0, 4).map((q, i) => (
          <div 
            key={i} 
            className="bg-white border border-[#F4DFD7]/80 rounded-2xl p-5 flex items-start gap-3.5 hover:shadow-sm transition-all duration-200"
          >
            <div className="w-6 h-6 rounded-full bg-[#8FA998]/15 border border-[#8FA998]/30 flex items-center justify-center text-[#586E5E] shrink-0 mt-0.5">
              <Check size={12} strokeWidth={3} />
            </div>
            <p className="text-xs md:text-sm text-[#5D3754] font-medium leading-relaxed">
              "{q}"
            </p>
          </div>
        ))}
        {questions.length === 0 && (
          <div className="col-span-2 text-center py-6 text-xs text-[#5D3754]/60 italic">
            No specific doctor questions were generated for this report.
          </div>
        )}
      </div>

      <div className="text-[11px] text-[#5D3754]/65 pt-2 border-t border-[#F4DFD7]/40 flex items-center gap-2">
        <span>💡</span>
        <span>Tip: Bring this checklist to your exam. Healthcare providers appreciate patients who are prepared and proactive.</span>
      </div>

    </div>
  );
}
